// Externalized UI strings (i18n-ready). PT-only in the MVP; adding EN later is swapping this
// object behind a locale switch, not retouching every component. No hardcoded copy in components.
export const t = {
	brand: 'rara',
	nav: {
		overview: 'Visão geral',
		pipeline: 'Pipeline',
		quarantine: 'Quarentena',
		distillations: 'Distillations',
		secTrain: 'Treinar',
		curation: 'Curadoria',
		fontes: 'Fontes',
		workers: 'Workers',
		agents: 'Agents',
		secSystem: 'Sistema',
		audit: 'Auditoria',
		settings: 'Configurações'
	},
	topbar: {
		search: 'Buscar ou comandar…'
	},
	status: { online: 'VPC Oracle · online', offline: 'core inacessível' },
	overview: {
		title: 'Visão geral',
		kpiFlows: 'Flows',
		kpiProviders: 'Providers',
		kpiEnabled: 'Providers ativos',
		flowsPanel: 'Flows configurados',
		providersPanel: 'Providers registrados',
		loading: 'Carregando do core ao vivo…',
		error: 'Não foi possível ler a superfície do core.',
		empty: 'Nada seedado ainda.'
	},
	pipeline: {
		title: 'Pipeline',
		loading: 'Carregando pipeline do core ao vivo…',
		error: 'Não foi possível ler o pipeline do core.',
		empty: 'Nenhum item no pipeline ainda.',
		emptyStatus: 'Nenhum item nesta fila.',
		stepsLoading: 'Carregando etapas…',
		stepsEmpty: 'Sem etapas registradas.',
		stepsError: 'Erro ao carregar etapas.',
		colCapability: 'Capability',
		colProvider: 'Provider',
		colStatus: 'Status',
		colAttempts: 'Tentativas',
		statusLabels: {
			discovered: 'Descoberto',
			to_text: 'Para texto',
			distilled: 'Destilado',
			done: 'Concluído',
			filtered: 'Filtrado',
			quarantine: 'Quarentena',
			failed: 'Falhou'
		}
	},
	quarantine: {
		title: 'Quarentena',
		loading: 'Carregando quarentena…',
		error: 'Não foi possível ler a quarentena.',
		empty: 'Nenhum item em quarentena.',
		rescue: 'Me interesso',
		confirmDrop: 'Não me interessa',
		reviewing: 'Processando…',
		reviewError: 'Erro ao processar decisão.',
		retry: 'Tentar novamente',
		keyboardHint: 'y = Me interesso · n = Não me interessa · j/k = navegar'
	},
	distillations: {
		title: 'Distillations',
		loading: 'Carregando distillations…',
		error: 'Não foi possível ler as distillations.',
		empty: 'Nenhuma distillation ainda.',
		detailLoading: 'Carregando…',
		detailError: 'Não foi possível carregar a distillation.',
		thumbUp: '👍',
		thumbDown: '👎',
		feedbackSent: 'Feedback registrado.',
		feedbackError: 'Erro ao registrar feedback.',
		retry: 'Tentar novamente',
		back: '← Voltar'
	},
	workers: {
		title: 'Workers',
		loading: 'Carregando workers…',
		error: 'Não foi possível carregar os workers.',
		empty: 'Nenhum worker registrado.',
		colName: 'Nome',
		colCapability: 'Capability',
		colRuntime: 'Runtime',
		colActivation: 'Ativação',
		colEnabled: 'Ativo',
		colLastRun: 'Última execução',
		lastRunNever: 'Nunca executou',
		enable: 'Ativar',
		disable: 'Desativar',
		saving: 'Salvando…',
		saveError: 'Erro ao salvar worker.',
		// CRUD form
		colWorker: 'Worker',
		colPlacements: 'Placements',
		placementsCount: 'placement(s)',
		expandPlacements: 'Expandir placements',
		collapsePlacements: 'Recolher placements',
		enabledStatus: 'ativo',
		disabledStatus: 'inativo',
		addWorker: 'Novo worker',
		addPlacement: 'Adicionar placement',
		formTitleAddPlacement: 'Adicionar placement',
		editWorker: 'Editar placement',
		formWorker: 'Worker',
		formWorkerPlaceholder: 'ex: distill',
		formWorkerReadonly: 'Worker (agrupador — não editável)',
		formWorkerRequired: 'Worker é obrigatório.',
		formName: 'Nome (placement)',
		formNamePlaceholder: 'ex: distill-vpc',
		formNameReadonly: 'Nome (chave — não editável)',
		formCapability: 'Capability',
		formCapabilityReadonly: 'Capability (identidade — não editável)',
		formCapabilityPlaceholder: 'ex: distill',
		formRuntime: 'Runtime',
		formRuntimeReadonly: 'Runtime (identidade — não editável)',
		formRuntimeConstraint: 'Runtime não permitido pela restrição do worker (requer IP residencial — use local).',
		formActivation: 'Ativação',
		formEnabled: 'Ativo',
		formConstraints: 'Restrições',
		formConstraintsRequires: 'Requires',
		formConstraintsRequiresNone: '—',
		formConstraintsRequiresResidential: 'residential',
		formConstraintsAccepts: 'Lanes aceitas (vírgula)',
		formConstraintsAcceptsPlaceholder: 'ex: podcast, youtube',
		formConstraintsSensitivity: 'Sensitivity',
		formConstraintsSensitivityNone: '—',
		formConstraintsSensitivityThirdParty: 'third_party',
		formRunnerUrl: 'Runner URL',
		formRunnerUrlPlaceholder: 'https://host.tailnet:8080 (vazio p/ cloudrun)',
		formEnv: 'Env (JSON objeto)',
		formEnvPlaceholder: '{"KEY": "value"}',
		formEnvInvalid: 'Env deve ser um objeto JSON válido.',
		formSave: 'Salvar',
		formCancel: 'Cancelar',
		formNameRequired: 'Nome é obrigatório.',
		formCapabilityRequired: 'Capability é obrigatória.',
		formRuntimeInvalid: 'Runtime deve ser local, cloudrun ou vpc.',
		formActivationInvalid: 'Ativação deve ser resident ou on_demand.',
		formRunnerUrlInvalidFormat: 'Runner URL inválida.',
		formRunnerUrlInvalidScheme: 'Runner URL deve usar http ou https.',
		formRunnerUrlInvalidHost: 'Runner URL não pode apontar para loopback.',
		formEnvValuesInvalid: 'Env: todos os valores devem ser strings.',
		policiesSection: 'Roteamento',
		policiesLoading: 'Carregando políticas…',
		policiesError: 'Não foi possível carregar as políticas de roteamento.',
		policiesEmpty: 'Nenhuma política configurada.',
		colScope: 'Escopo',
		policyScopeGlobal: 'global',
		policyFallbackSection: 'Fallback',
		policyFallbackEmpty: 'Sem fallback definido — usa default do roteador.',
		policySaveBtn: 'Salvar política',
		policySaving: 'Salvando…',
		policySaveOk: 'Política salva.',
		policySaveError: 'Erro ao salvar política de roteamento.',
		fallbackMoveUp: 'mover para cima',
		fallbackMoveDown: 'mover para baixo',
		fallbackRemove: 'remover',
		metricsSection: 'Métricas',
		period1d: '24h',
		period7d: '7d',
		period30d: '30d',
		periodAll: 'Tudo',
		nowBadge: 'agora',
		cardHealth: 'Saúde & atividade',
		cardReliability: 'Confiabilidade',
		cardVolume: 'Volume & share',
		cardQueue: 'Fila atual',
		metricsError: 'Não foi possível carregar as métricas.',
		metricsEmpty: 'Sem atividade no período.',
		lastActivity: 'Última atividade',
		never: 'Nunca',
		stale: 'stale',
		asleep: 'dormindo',
		failuresInPeriod: 'falhas no período',
		topErrorWorker: 'Maior share de erro',
		successItems: 'itens com sucesso',
		queuePending: 'pendente',
		queueAssigned: 'atribuído',
		queueRunning: 'em execução',
		lastError: 'Última falha',
		lastErrorLabel: 'Erro no último dispatch',
		// step-host routing (per-flow-step priority list)
		hostsUp: '↑',
		hostsDown: '↓',
		hostsRemove: '×',
		hostsAddPlaceholder: 'Adicionar host…',
		// ── Fontes-style redesign (Task 3 #244) ──
		searchToggle: 'Buscar workers',
		searchPlaceholder: 'Buscar por worker ou placement…',
		filterClear: 'Limpar filtros ✕',
		colType: 'Tipo',
		colWorkerGroup: 'Worker',
		sortAZ: 'A → Z',
		sortZA: 'Z → A',
		sortNewest: 'Mais recente',
		sortOldest: 'Mais antigo',
		filterAllCapability: 'Todos os tipos',
		filterAllRuntime: 'Todos os runtimes',
		filterAllActivation: 'Todas as ativações',
		filterAllStatus: 'Todos os status',
		actionsLabel: 'Ações',
		emptyFiltered: 'Nenhum worker para os filtros atuais.',
		saveOkToast: 'Salvo.'
	},
	agents: {
		title: 'Agents',
		soon: 'Em breve',
		blurb: 'Agentes de IA autônomos que decidem, executam e aprendem — o próximo passo da plataforma rara.'
	},
	fontes: {
		title: 'Fontes',
		loading: 'Carregando fontes do core ao vivo…',
		error: 'Não foi possível carregar as fontes.',
		empty: 'Nenhuma fonte cadastrada.',
		emptyFiltered: 'Nenhuma fonte para os filtros atuais.',
		searchPlaceholder: 'Buscar por nome ou config…',
		filterAllKinds: 'Todos os tipos',
		filterAllStatus: 'Todos os status',
		filterClear: 'Limpar filtros',
		colSortAZ: 'A → Z',
		colSortZA: 'Z → A',
		colSortNewest: 'Mais recente',
		colSortOldest: 'Mais antigo',
		colName: 'Fonte',
		colKind: 'Tipo',
		colLane: 'Lane',
		colStatus: 'Status',
		colUpdated: 'Última atividade',
		statusActive: 'ativa',
		statusPaused: 'pausada',
		never: '—',
		count: 'fonte',
		countPlural: 'fontes',
		// actions
		newSource: 'Nova fonte',
		actionEdit: 'Editar',
		actionDelete: 'Excluir',
		actionPause: 'Pausar',
		actionResume: 'Retomar',
		// wizard
		wizardStep1Title: 'Escolha o tipo da fonte',
		wizardStep2Title: 'Configurar {kind}',
		wizardBack: '← Voltar',
		wizardCancel: 'Cancelar',
		wizardCreate: 'Criar fonte',
		wizardCreating: 'Criando…',
		wizardRequired: 'Campo obrigatório.',
		wizardCreateOk: 'Fonte criada.',
		wizardCreateError: 'Não foi possível criar a fonte.',
		// edit
		editTitle: 'Editar fonte',
		editDisplayName: 'Nome de exibição',
		editTags: 'Tags',
		editTagAdd: 'Adicionar tag…',
		editTagRemove: 'Remover tag',
		editSave: 'Salvar',
		editSaving: 'Salvando…',
		editSaveOk: 'Fonte atualizada.',
		editSaveError: 'Não foi possível salvar a fonte.',
		editLoading: 'Carregando campos…',
		// delete
		deleteTitle: 'Excluir fonte',
		deleteConfirm: 'Excluir “{name}”? O cadastro some da lista; o conteúdo já coletado é preservado.',
		deleteCancel: 'Cancelar',
		deleteConfirmBtn: 'Excluir',
		deleting: 'Excluindo…',
		deleteOk: 'Fonte excluída.',
		deleteError: 'Não foi possível excluir a fonte.',
		// pause/resume toasts
		pauseOk: 'Fonte pausada.',
		resumeOk: 'Fonte retomada.',
		pauseError: 'Não foi possível alterar o status.',
		// pagination (server-side) — every page is reachable, so there is no truncation notice
		pageRange: '{from}–{to} de {total}',
		pagePrev: 'Página anterior',
		pageNext: 'Próxima página',
		pageOf: '{page}/{pages}',
		// selection + bulk
		selectAllPage: 'Selecionar a página',
		selectRow: 'Selecionar fonte',
		selectAllPageBanner: 'As {n} fontes desta página estão selecionadas.',
		selectAllFilterBtn: 'Selecionar todas as {total}',
		selectAllCapNote: '(máx. {cap})',
		selectingAll: 'Selecionando…',
		selectedCount: '{n} fonte selecionada',
		selectedCountPlural: '{n} fontes selecionadas',
		bulkClear: 'Limpar seleção',
		bulkPause: 'Pausar',
		bulkResume: 'Retomar',
		bulkTag: 'Taguear',
		bulkUntag: 'Destaguear',
		bulkDelete: 'Excluir',
		bulkTagPlaceholder: 'tag…',
		bulkApplying: 'Aplicando…',
		bulkResultOk: '{ok} aplicada(s).',
		bulkResultPartial: '{ok} aplicada(s), {fail} falha(s).',
		bulkError: 'Não foi possível aplicar a ação em lote.',
		bulkDeleteTitle: 'Excluir fontes selecionadas',
		bulkDeleteConfirm:
			'Excluir {n} fonte(s)? O cadastro some da lista; o conteúdo já coletado é preservado.'
	},
	auditoria: {
		title: 'Auditoria',
		loading: 'Carregando decisões…',
		error: 'Não foi possível carregar o feed de decisões.',
		empty: 'Nenhuma decisão registrada ainda.',
		colID: 'ID',
		colItem: 'Item',
		colGate: 'Gate',
		colDecision: 'Decisão',
		colScore: 'Score',
		colWhen: 'Quando',
		keep: 'keep',
		drop: 'drop',
		defer: 'defer',
		limitLabel: 'Últimas',
		itemLink: '→'
	},
	cmdPalette: {
		placeholder: 'Ir para…',
		noResults: 'Nenhum resultado.'
	},
	settings: {
		title: 'Configurações',
		healthSection: 'Saúde do sistema',
		dbOk: 'Banco de dados',
		dbOkYes: 'OK',
		dbOkNo: 'Falhou',
		lastReconcile: 'Último reconcile',
		never: 'Nunca',
		providersTotal: 'Providers registrados',
		providersEnabled: 'Providers ativos',
		providersStale: 'Providers desatualizados',
		usageSection: 'Uso',
		distillationsTotal: 'Distillations',
		quarantineTotal: 'Quarentena',
		itemsSection: 'Items por lane e status',
		stepsSection: 'Etapas por capability e status',
		colLane: 'Lane',
		colCapability: 'Capability',
		colStatus: 'Status',
		colCount: 'Contagem',
		billingSection: 'Custos',
		billingNote: 'Custos exatos requerem o export do GCP Billing — não é possível calculá-los aqui.',
		billingLink: 'Abrir GCP Billing',
		// routing section (moved from workers)
		routingSection: 'Roteamento',
		metricsWorkersSection: 'Métricas Workers',
		workersLoadError: 'Não foi possível carregar os workers.',
		loading: 'Carregando configurações…',
		error: 'Não foi possível carregar as configurações.'
	},
	curadoria: {
		title: 'Curadoria',
		// cockpit zones
		pulsoZone: 'Pulso',
		pulsoLabel: '~24h',
		pulsoEntrou: 'Entrou',
		pulsoManteve: 'Manteve',
		pulsoBarrou: 'Barrou',
		pulsoDuvida: 'Em dúvida',
		spineStep1: 'entrou',
		spineStep2: 'gate decidiu',
		spineStep3: 'você revisa a dúvida',
		spineStep4: 'molda o gosto',
		filaZone: 'Fila de revisão',
		filaSubtitle: 'aguardando · ←/→ p/ decidir',
		filaEmpty: 'Sem itens em dúvida.',
		filaComingSoon: 'em breve',
		filaKeep: 'Manter',
		filaDrop: 'Descartar',
		filaLoading: 'Carregando fila…',
		filaError: 'Não foi possível carregar a fila.',
		filaWhyFence: 'por que ficou na cerca',
		filaDecidedBy: 'decidido por',
		filaReason: 'motivo',
		filaReviewError: 'Erro ao registrar veredito.',
		gostoZone: 'O gosto',
		trilhaZone: 'Trilha de decisões',
		trilhaEmpty: 'Sem decisões registradas.',
		trilhaLoading: 'Carregando decisões…',
		trilhaError: 'Não foi possível carregar as decisões.',
		trilhaItemRef: 'item',
		trilhaDecidedByLabel: 'por',
		pulsoLoading: 'Carregando…',
		pulsoError: 'Não foi possível carregar.',
		pulsoProposedPending: 'Revisão de perfil pendente →',
		gateExpand: 'Expandir',
		gateCollapse: 'Recolher',
		profileSection: 'Interest Profile',
		profileLoading: 'Carregando interest profile…',
		profileError: 'Não foi possível carregar o interest profile.',
		profileEmpty: 'Nenhum interest profile ativo. Proponha a primeira versão abaixo.',
		profileCurrent: 'Versão ativa',
		profileNone: 'Nenhuma versão ativa.',
		profileVersions: 'Histórico de versões',
		profileVersion: 'Versão',
		profileStatus: 'Status',
		profileCreatedAt: 'Criado em',
		profileNarrative: 'Narrativa',
		profileApprove: 'Aprovar',
		profileApproving: 'Aprovando…',
		profileApproveError: 'Erro ao aprovar versão.',
		profileProposeSection: 'Propor nova versão',
		profileVersionLabel: 'Versão (inteiro positivo)',
		profileNarrativeLabel: 'Narrativa',
		profileTopicsLabel: 'Topics (JSON)',
		profileAuthorsLabel: 'Authors (JSON)',
		profileAntiTopicsLabel: 'Anti-topics (JSON)',
		profileWeightsLabel: 'Weights (JSON)',
		profileProposeBtn: 'Propor versão',
		profileProposing: 'Propondo…',
		profileProposeError: 'Erro ao propor versão.',
		profileJsonHint: 'JSON opcional — ex: ["go","observabilidade"]',
		profileStable: 'Perfil estável, sem revisão pendente.',
		profileProposedCard: 'revisão proposta',
		profileProposedNarrative: 'Narrativa do juiz',
		profileDiffAdded: 'adicionado',
		profileDiffRemoved: 'removido',
		profileDiffChanged: 'alterado',
		profileDiffNoChanges: 'Sem alterações neste campo.',
		profileDiffFallback: 'Formato inesperado — diferença não computada.',
		profileApproveBtn: (v: number) => `Aprovar v${v}`,
		gateSection: 'Regras de gate',
		gateLoading: 'Carregando regras…',
		gateError: 'Não foi possível carregar as regras.',
		gateEmpty: 'Nenhuma regra configurada.',
		gateAction: 'Ação',
		gateMatchType: 'Tipo de match',
		gateValue: 'Valor',
		gateEnabled: 'Ativa',
		gateSave: 'Salvar regra',
		gateSaving: 'Salvando…',
		gateSaveError: 'Erro ao salvar regra.',
		gateEdit: 'Editar',
		gateToggle: 'Ligar/desligar',
		gateAddSection: 'Adicionar / editar regra'
	}
};
