// Externalized UI strings (i18n-ready). PT-only in the MVP; adding EN later is swapping this
// object behind a locale switch, not retouching every component. No hardcoded copy in components.
export const t = {
	brand: 'rara',
	nav: {
		overview: 'Visão geral',
		pipeline: 'Pipeline',
		quarantine: 'Quarentena',
		distillations: 'Distillations',
		secTrain: 'Treinar',
		curation: 'Curadoria',
		sources: 'Fontes & Flows',
		providers: 'Providers & Roteamento',
		secSystem: 'Sistema',
		audit: 'Auditoria',
		settings: 'Configurações'
	},
	topbar: {
		search: 'Buscar ou comandar…'
	},
	status: { online: 'VPC Oracle · online', offline: 'core inacessível' },
	overview: {
		title: 'Visão geral',
		kpiFlows: 'Flows',
		kpiProviders: 'Providers',
		kpiEnabled: 'Providers ativos',
		flowsPanel: 'Flows configurados',
		providersPanel: 'Providers registrados',
		loading: 'Carregando do core ao vivo…',
		error: 'Não foi possível ler a superfície do core.',
		empty: 'Nada seedado ainda.'
	},
	pipeline: {
		title: 'Pipeline',
		loading: 'Carregando pipeline do core ao vivo…',
		error: 'Não foi possível ler o pipeline do core.',
		empty: 'Nenhum item no pipeline ainda.',
		emptyStatus: 'Nenhum item nesta fila.',
		stepsLoading: 'Carregando etapas…',
		stepsEmpty: 'Sem etapas registradas.',
		stepsError: 'Erro ao carregar etapas.',
		colCapability: 'Capability',
		colProvider: 'Provider',
		colStatus: 'Status',
		colAttempts: 'Tentativas',
		statusLabels: {
			discovered: 'Descoberto',
			to_text: 'Para texto',
			distilled: 'Destilado',
			done: 'Concluído',
			filtered: 'Filtrado',
			quarantine: 'Quarentena',
			failed: 'Falhou'
		}
	},
	quarantine: {
		title: 'Quarentena',
		loading: 'Carregando quarentena…',
		error: 'Não foi possível ler a quarentena.',
		empty: 'Nenhum item em quarentena.',
		rescue: 'Me interesso',
		confirmDrop: 'Não me interessa',
		reviewing: 'Processando…',
		reviewError: 'Erro ao processar decisão.',
		retry: 'Tentar novamente'
	},
	distillations: {
		title: 'Distillations',
		loading: 'Carregando distillations…',
		error: 'Não foi possível ler as distillations.',
		empty: 'Nenhuma distillation ainda.',
		detailLoading: 'Carregando…',
		detailError: 'Não foi possível carregar a distillation.',
		thumbUp: '👍',
		thumbDown: '👎',
		feedbackSent: 'Feedback registrado.',
		feedbackError: 'Erro ao registrar feedback.',
		retry: 'Tentar novamente',
		back: '← Voltar'
	},
	providers: {
		title: 'Providers & Roteamento',
		loading: 'Carregando providers…',
		error: 'Não foi possível carregar os providers.',
		empty: 'Nenhum provider registrado.',
		colName: 'Nome',
		colCapability: 'Capability',
		colRuntime: 'Runtime',
		colActivation: 'Ativação',
		colCost: 'Custo',
		colQuality: 'Qualidade',
		colLatency: 'Latência (ms)',
		colEnabled: 'Ativo',
		saving: 'Salvando…',
		saveError: 'Erro ao salvar provider.',
		saveOk: 'Salvo.',
		policiesSection: 'Roteamento',
		policiesLoading: 'Carregando políticas…',
		policiesError: 'Não foi possível carregar as políticas de roteamento.',
		policiesEmpty: 'Nenhuma política configurada.',
		colScope: 'Escopo',
		colCostWeight: 'Peso custo',
		colQualityWeight: 'Peso qualidade',
		colLatencyWeight: 'Peso latência'
	},
	fontesFlows: {
		title: 'Fontes & Flows',
		sourcesSection: 'Fontes — feeds de podcast',
		sourcesLoading: 'Carregando feeds…',
		sourcesError: 'Não foi possível carregar os feeds.',
		sourcesEmpty: 'Nenhum feed cadastrado. Adicione o primeiro abaixo.',
		colURL: 'URL do feed',
		colTitle: 'Título',
		colActive: 'Ativo',
		titlePending: '— (preenchido na coleta)',
		addPlaceholder: 'https://exemplo.com/feed.xml',
		addBtn: 'Adicionar feed',
		adding: 'Adicionando…',
		addError: 'Não foi possível adicionar o feed.',
		activate: 'Ativar',
		deactivate: 'Desativar',
		saving: 'Salvando…',
		saveError: 'Erro ao salvar.',
		flowsSection: 'Flows — lanes do pipeline',
		flowsLoading: 'Carregando flows…',
		flowsError: 'Não foi possível carregar os flows.',
		flowsEmpty: 'Nenhum flow configurado.',
		colName: 'Nome',
		colSourceType: 'Tipo de fonte',
		colVersion: 'Versão',
		colEnabled: 'Ativo',
		stepsToggle: 'Etapas',
		stepsLoading: 'Carregando etapas…',
		stepsEmpty: 'Sem etapas registradas.',
		stepsError: 'Erro ao carregar etapas.',
		colSeq: 'Seq',
		colCapability: 'Capability'
	},
	auditoria: {
		title: 'Auditoria',
		loading: 'Carregando decisões…',
		error: 'Não foi possível carregar o feed de decisões.',
		empty: 'Nenhuma decisão registrada ainda.',
		colID: 'ID',
		colItem: 'Item',
		colGate: 'Gate',
		colDecision: 'Decisão',
		colScore: 'Score',
		colWhen: 'Quando',
		keep: 'keep',
		drop: 'drop',
		defer: 'defer',
		limitLabel: 'Últimas',
		itemLink: '→'
	},
	cmdPalette: {
		placeholder: 'Ir para…',
		noResults: 'Nenhum resultado.'
	},
	curadoria: {
		title: 'Curadoria',
		profileSection: 'Interest Profile',
		profileLoading: 'Carregando interest profile…',
		profileError: 'Não foi possível carregar o interest profile.',
		profileEmpty: 'Nenhum interest profile ativo. Proponha a primeira versão abaixo.',
		profileCurrent: 'Versão ativa',
		profileNone: 'Nenhuma versão ativa.',
		profileVersions: 'Histórico de versões',
		profileVersion: 'Versão',
		profileStatus: 'Status',
		profileCreatedAt: 'Criado em',
		profileNarrative: 'Narrativa',
		profileApprove: 'Aprovar',
		profileApproving: 'Aprovando…',
		profileApproveError: 'Erro ao aprovar versão.',
		profileProposeSection: 'Propor nova versão',
		profileVersionLabel: 'Versão (inteiro positivo)',
		profileNarrativeLabel: 'Narrativa',
		profileTopicsLabel: 'Topics (JSON)',
		profileAuthorsLabel: 'Authors (JSON)',
		profileAntiTopicsLabel: 'Anti-topics (JSON)',
		profileWeightsLabel: 'Weights (JSON)',
		profileProposeBtn: 'Propor versão',
		profileProposing: 'Propondo…',
		profileProposeError: 'Erro ao propor versão.',
		profileJsonHint: 'JSON opcional — ex: ["go","observabilidade"]',
		gateSection: 'Regras de gate',
		gateLoading: 'Carregando regras…',
		gateError: 'Não foi possível carregar as regras.',
		gateEmpty: 'Nenhuma regra configurada.',
		gateAction: 'Ação',
		gateMatchType: 'Tipo de match',
		gateValue: 'Valor',
		gateEnabled: 'Ativa',
		gateSave: 'Salvar regra',
		gateSaving: 'Salvando…',
		gateSaveError: 'Erro ao salvar regra.',
		gateEdit: 'Editar',
		gateToggle: 'Ligar/desligar',
		gateAddSection: 'Adicionar / editar regra'
	}
};
