// Externalized UI strings (i18n-ready). PT-only in the MVP; adding EN later is swapping this
// object behind a locale switch, not retouching every component. No hardcoded copy in components.
export const t = {
	brand: 'rara',
	nav: {
		overview: 'Visão geral',
		pipeline: 'Pipeline',
		distillations: 'Distillations',
		secTrain: 'Treinar',
		curation: 'Curadoria',
		fontes: 'Fontes',
		workers: 'Workers',
		inferencia: 'Providers',
		skills: 'Skills',
		agents: 'Agents',
		secSystem: 'Sistema',
		audit: 'Auditoria',
		settings: 'Configurações'
	},
	topbar: {
		search: 'Buscar ou comandar…'
	},
	status: { online: 'VPC Oracle · online', offline: 'core inacessível' },
	overview: {
		title: 'Visão geral',
		kpiFlows: 'Flows',
		kpiProviders: 'Providers',
		kpiEnabled: 'Providers ativos',
		flowsPanel: 'Flows configurados',
		providersPanel: 'Providers registrados',
		loading: 'Carregando do core ao vivo…',
		error: 'Não foi possível ler a superfície do core.',
		empty: 'Nada seedado ainda.'
	},
	pipeline: {
		title: 'Pipeline',
		loading: 'Carregando pipeline do core ao vivo…',
		error: 'Não foi possível ler o pipeline do core.',
		empty: 'Nenhum item no pipeline ainda.',
		emptyStatus: 'Nenhum item nesta fila.',
		stepsLoading: 'Carregando etapas…',
		stepsEmpty: 'Sem etapas registradas.',
		stepsError: 'Erro ao carregar etapas.',
		colCapability: 'Capability',
		colProvider: 'Provider',
		colStatus: 'Status',
		colAttempts: 'Tentativas',
		statusLabels: {
			discovered: 'Descoberto',
			to_text: 'Para texto',
			distilled: 'Destilado',
			done: 'Concluído',
			filtered: 'Filtrado',
			quarantine: 'Quarentena',
			failed: 'Falhou'
		}
	},
	distillations: {
		title: 'Distillations',
		loading: 'Carregando distillations…',
		error: 'Não foi possível ler as distillations.',
		empty: 'Nenhuma distillation ainda.',
		detailLoading: 'Carregando…',
		detailError: 'Não foi possível carregar a distillation.',
		thumbUp: '👍',
		thumbDown: '👎',
		feedbackSent: 'Feedback registrado.',
		feedbackError: 'Erro ao registrar feedback.',
		retry: 'Tentar novamente',
		back: '← Voltar'
	},
	workers: {
		title: 'Workers',
		loading: 'Carregando workers…',
		error: 'Não foi possível carregar os workers.',
		empty: 'Nenhum worker registrado.',
		colName: 'Nome',
		colCapability: 'Capability',
		colRuntime: 'Runtime',
		colActivation: 'Ativação',
		colEnabled: 'Ativo',
		colLastRun: 'Última execução',
		lastRunNever: 'Nunca executou',
		enable: 'Ativar',
		disable: 'Desativar',
		saving: 'Salvando…',
		saveError: 'Erro ao salvar worker.',
		// CRUD form
		colWorker: 'Worker',
		colPlacements: 'Placements',
		placementsCount: 'placement(s)',
		expandPlacements: 'Expandir placements',
		collapsePlacements: 'Recolher placements',
		enabledStatus: 'ativo',
		disabledStatus: 'inativo',
		addWorker: 'Novo worker',
		addPlacement: 'Adicionar placement',
		formTitleAddPlacement: 'Adicionar placement',
		editWorker: 'Editar placement',
		formWorker: 'Worker',
		formWorkerPlaceholder: 'ex: distill',
		formWorkerReadonly: 'Worker (agrupador — não editável)',
		formWorkerRequired: 'Worker é obrigatório.',
		formName: 'Nome (placement)',
		formNamePlaceholder: 'ex: distill-vpc',
		formNameReadonly: 'Nome (chave — não editável)',
		formCapability: 'Capability',
		formCapabilityReadonly: 'Capability (identidade — não editável)',
		formCapabilityPlaceholder: 'ex: distill',
		formRuntime: 'Runtime',
		formRuntimeReadonly: 'Runtime (identidade — não editável)',
		formRuntimeConstraint: 'Runtime não permitido pela restrição do worker (requer IP residencial — use local).',
		formActivation: 'Ativação',
		formEnabled: 'Ativo',
		formConstraints: 'Restrições',
		formConstraintsRequires: 'Requires',
		formConstraintsRequiresNone: '—',
		formConstraintsRequiresResidential: 'residential',
		formConstraintsAccepts: 'Lanes aceitas (vírgula)',
		formConstraintsAcceptsPlaceholder: 'ex: podcast, youtube',
		formConstraintsSensitivity: 'Sensitivity',
		formConstraintsSensitivityNone: '—',
		formConstraintsSensitivityThirdParty: 'third_party',
		formProvider: 'Provider (LLM)',
		formProviderNone: '— selecione —',
		formModel: 'Model (LLM)',
		formModelNone: '— nenhum —',
		formModelManualPlaceholder: 'ex: gpt-4o (entrada livre p/ BYO)',
		formModelInvalid: 'Model inválido — sem espaços nem quebras de linha.',
		formModelCloudrunHint: 'Propaga ao Cloud Run no próximo sync.',
		formModelLoadFailed: 'Não foi possível carregar provedores/models — recarregue para definir o Model.',
		formModelLoading: 'Carregando provedores/models…',
		formRunnerUrl: 'Runner URL',
		formRunnerUrlPlaceholder: 'https://host.tailnet:8080 (vazio p/ cloudrun)',
		formEnv: 'Env (JSON objeto)',
		formEnvPlaceholder: '{"KEY": "value"}',
		formEnvInvalid: 'Env deve ser um objeto JSON válido.',
		formSave: 'Salvar',
		formCancel: 'Cancelar',
		formNameRequired: 'Nome é obrigatório.',
		formCapabilityRequired: 'Capability é obrigatória.',
		formRuntimeInvalid: 'Runtime deve ser local, cloudrun ou vpc.',
		formActivationInvalid: 'Ativação deve ser resident ou on_demand.',
		formRunnerUrlInvalidFormat: 'Runner URL inválida.',
		formRunnerUrlInvalidScheme: 'Runner URL deve usar http ou https.',
		formRunnerUrlInvalidHost: 'Runner URL não pode apontar para loopback.',
		formEnvValuesInvalid: 'Env: todos os valores devem ser strings.',
		policiesSection: 'Roteamento',
		policiesLoading: 'Carregando políticas…',
		policiesError: 'Não foi possível carregar as políticas de roteamento.',
		policiesEmpty: 'Nenhuma política configurada.',
		colScope: 'Escopo',
		policyScopeGlobal: 'global',
		policyFallbackSection: 'Fallback',
		policyFallbackEmpty: 'Sem fallback definido — usa default do roteador.',
		policySaveBtn: 'Salvar política',
		policySaving: 'Salvando…',
		policySaveOk: 'Política salva.',
		policySaveError: 'Erro ao salvar política de roteamento.',
		fallbackMoveUp: 'mover para cima',
		fallbackMoveDown: 'mover para baixo',
		fallbackRemove: 'remover',
		metricsSection: 'Métricas',
		period1d: '24h',
		period7d: '7d',
		period30d: '30d',
		periodAll: 'Tudo',
		nowBadge: 'agora',
		cardHealth: 'Saúde & atividade',
		cardReliability: 'Confiabilidade',
		cardVolume: 'Volume & share',
		cardQueue: 'Fila atual',
		metricsError: 'Não foi possível carregar as métricas.',
		metricsEmpty: 'Sem atividade no período.',
		lastActivity: 'Última atividade',
		never: 'Nunca',
		stale: 'stale',
		asleep: 'dormindo',
		failuresInPeriod: 'falhas no período',
		topErrorWorker: 'Maior share de erro',
		successItems: 'itens com sucesso',
		queuePending: 'pendente',
		queueAssigned: 'atribuído',
		queueRunning: 'em execução',
		lastError: 'Última falha',
		lastErrorLabel: 'Erro no último dispatch',
		// step-host routing (per-flow-step priority list)
		hostsUp: '↑',
		hostsDown: '↓',
		hostsRemove: '×',
		hostsAddPlaceholder: 'Adicionar host…',
		// ── Fontes-style redesign (Task 3 #244) ──
		searchToggle: 'Buscar workers',
		searchPlaceholder: 'Buscar por worker ou placement…',
		filterClear: 'Limpar filtros ✕',
		colType: 'Tipo',
		colWorkerGroup: 'Worker',
		sortAZ: 'A → Z',
		sortZA: 'Z → A',
		sortNewest: 'Mais recente',
		sortOldest: 'Mais antigo',
		filterAllCapability: 'Todos os tipos',
		filterAllRuntime: 'Todos os runtimes',
		filterAllActivation: 'Todas as ativações',
		filterAllStatus: 'Todos os status',
		actionsLabel: 'Ações',
		emptyFiltered: 'Nenhum worker para os filtros atuais.',
		saveOkToast: 'Salvo.'
	},
	agents: {
		title: 'Agents',
		subtitle: 'Personas de IA — instruções, modelo e skills anexadas que o daemon executa.',
		loading: 'Carregando agents…',
		error: 'Não foi possível carregar os agents.',
		empty: 'Nenhum agent ainda. Crie o primeiro.',
		add: 'Novo agent',
		create: 'Criar agent',
		edit: 'Editar agent',
		untitled: '(sem nome)',
		nameLabel: 'Nome',
		namePlaceholder: 'Docslide Writer',
		descLabel: 'Descrição',
		descPlaceholder: 'O que este agent faz',
		avatarLabel: 'Avatar (URL)',
		avatarPlaceholder: 'https://…',
		visibilityLabel: 'Visibilidade',
		visibilityWorkspace: 'Workspace',
		visibilityPrivate: 'Pessoal',
		providerLabel: 'Provider',
		providerNone: '— escolher —',
		modelLabel: 'Modelo',
		modelNone: '— escolher —',
		modelManualPlaceholder: 'modelo (texto livre)',
		modelLoading: 'Carregando providers…',
		modelLoadFailed: 'Falha ao carregar providers — recarregue.',
		modelInvalid: 'Modelo inválido (sem espaços/quebras de linha).',
		instructionsLabel: 'Instruções (system prompt)',
		instructionsPlaceholder: 'Você é um agent que…',
		skillsLabel: 'Skills',
		skillsEmpty: 'Nenhuma skill disponível.',
		save: 'Salvar',
		saving: 'Salvando…',
		cancel: 'Cancelar',
		delete: 'Excluir',
		deleting: 'Excluindo…',
		deleteConfirm: 'Excluir o agent "{name}"? Esta ação não pode ser desfeita.',
		errNameRequired: 'Nome é obrigatório.',
		saveOk: 'Salvo.',
		saveError: 'Não foi possível salvar.',
		skillsSaveError: 'Agent salvo, mas não foi possível salvar as skills. Tente novamente.',
		deleteOk: 'Excluído.',
		deleteError: 'Não foi possível excluir.'
	},
	skills: {
		title: 'Skills',
		subtitle: 'Bundles SKILL.md + arquivos de apoio — instruções e scripts que o daemon executa.',
		loading: 'Carregando skills…',
		error: 'Não foi possível carregar as skills.',
		empty: 'Nenhuma skill ainda. Crie ou importe a primeira.',
		listTitle: 'Skills',
		add: 'Nova skill',
		import: 'Importar',
		untitled: '(sem nome)',
		trusted: 'Confiável',
		untrusted: 'Não confiável',
		trustToggle: 'Confiar',
		untrustToggle: 'Revogar confiança',
		trustHint: 'O daemon só executa scripts de skills confiáveis. Skills importadas nascem não confiáveis.',
		// editor
		nameLabel: 'Nome',
		namePlaceholder: 'ex.: linkedin-docslide',
		descLabel: 'Descrição',
		descPlaceholder: 'O que esta skill faz',
		contentLabel: 'SKILL.md',
		contentPlaceholder: '---\nname: minha-skill\ndescription: …\n---\n# Instruções',
		save: 'Salvar',
		saving: 'Salvando…',
		cancel: 'Cancelar',
		delete: 'Excluir',
		deleteConfirm: 'Excluir a skill “{name}”? Os arquivos do bundle vão junto.',
		deleting: 'Excluindo…',
		// files
		filesTitle: 'Arquivos do bundle',
		filesLoading: 'Carregando arquivos…',
		filesError: 'Não foi possível carregar os arquivos.',
		filesEmpty: 'Nenhum arquivo. Adicione utils.py, config.json…',
		addFile: 'Adicionar arquivo',
		filePathLabel: 'Caminho',
		filePathPlaceholder: 'ex.: utils.py',
		fileContentLabel: 'Conteúdo',
		fileSave: 'Salvar arquivo',
		fileDelete: 'Excluir',
		deleteFileConfirm: 'Excluir o arquivo “{path}” do bundle?',
		// import dialog
		importTitle: 'Importar skill',
		importUrlLabel: 'URL (ClawHub / skills.sh)',
		importUrlPlaceholder: 'https://…/SKILL.md',
		importHint: 'A skill é baixada como não confiável. Revise antes de confiar.',
		importBtn: 'Importar',
		importing: 'Importando…',
		// toasts
		saveOk: 'Salvo.',
		saveError: 'Não foi possível salvar.',
		deleteOk: 'Excluído.',
		deleteError: 'Não foi possível excluir.',
		importOk: 'Skill importada (não confiável).',
		importError: 'Não foi possível importar.',
		errNameRequired: 'O nome é obrigatório.',
		errUrlRequired: 'A URL é obrigatória.',
		errPathRequired: 'O caminho é obrigatório.',
		actionsLabel: 'Ações'
	},
	inferencia: {
		title: 'Inferência',
		// ── Providers section ──
		providersSection: 'Providers',
		providersSubtitle: 'Vendors e chaves — configuráveis sem deploy.',
		providersLoading: 'Carregando providers…',
		providersError: 'Não foi possível carregar os providers.',
		providersEmpty: 'Nenhum provider registrado.',
		providersEmptyFiltered: 'Nenhum provider para a busca atual.',
		colName: 'Nome',
		colKind: 'Tipo',
		colBaseUrl: 'Base URL',
		colKey: 'Chave',
		colEnabled: 'Ativo',
		addProvider: 'Novo provider',
		editProvider: 'Editar provider',
		formName: 'Nome',
		formNamePlaceholder: 'ex: groq-main',
		formNameReadonly: 'Nome (chave — não editável)',
		formKind: 'Tipo',
		formKindPlaceholder: 'busque um provider do litellm…',
		formKindHint: 'Qualquer provider do litellm (ou openai_compatible para BYO com Base URL).',
		formBaseUrl: 'Base URL',
		formBaseUrlPlaceholder: 'https://api.exemplo.com/v1',
		formApiKey: 'API key',
		formApiKeyPlaceholderNew: 'cole a chave do vendor',
		formApiKeyPlaceholderEdit: '•••• (manter)',
		formApiKeyHint: 'Write-only. Em branco mantém a chave atual.',
		formEnabled: 'Ativo',
		formSave: 'Salvar',
		formCancel: 'Cancelar',
		errNameRequired: 'Nome é obrigatório.',
		errApiKeyRequired: 'API key é obrigatória para um novo provider.',
		errBaseUrlRequired: 'Base URL é obrigatória para o tipo openai_compatible.',
		errBaseUrlInvalid: 'Base URL inválida.',
		errBaseUrlScheme: 'Base URL deve usar http ou https.',
		errBaseUrlPrivate: 'Base URL deve apontar para um host público.',
		errKindRequired: 'Tipo é obrigatório.',
		errKindDuplicate: 'Já existe um provider ativo deste tipo.',
		// ── shared ──
		searchToggle: 'Buscar',
		searchPlaceholder: 'Buscar por nome…',
		filterClear: 'Limpar busca ✕',
		sortAZ: 'A → Z',
		sortZA: 'Z → A',
		actionsLabel: 'Ações',
		enable: 'Ativar',
		disable: 'Desativar',
		edit: 'Editar',
		delete: 'Excluir',
		enabledStatus: 'ativo',
		disabledStatus: 'inativo',
		deleteProviderConfirm: 'Excluir o provider “{name}”? Workers que usam seus models param de resolver.',
		deleteConfirmBtn: 'Excluir',
		deleting: 'Excluindo…',
		saveOk: 'Salvo.',
		saveError: 'Erro ao salvar.',
		deleteOk: 'Excluído.',
		deleteError: 'Erro ao excluir.',
		// ── Gastos section (CORR-INFER-#4) ──
		gastosSection: 'Gastos',
		gastosSubtitle: 'Custo real do gateway (litellm) no período.',
		spend24h: '24h',
		spend7d: '7d',
		spend30d: '30d',
		spendAll: 'Tudo',
		spendLoading: 'Carregando gastos…',
		spendError: 'Não foi possível carregar os gastos.',
		spendEmpty: 'Sem gastos no período.',
		spendTotal: 'Total',
		chartOverallTitle: 'Gasto por dia',
		chartProviderTitle: 'Gasto por provider'
	},
	fontes: {
		title: 'Fontes',
		loading: 'Carregando fontes do core ao vivo…',
		error: 'Não foi possível carregar as fontes.',
		empty: 'Nenhuma fonte cadastrada.',
		emptyFiltered: 'Nenhuma fonte para os filtros atuais.',
		searchPlaceholder: 'Buscar por nome ou config…',
		filterAllKinds: 'Todos os tipos',
		filterAllStatus: 'Todos os status',
		filterClear: 'Limpar filtros',
		colSortAZ: 'A → Z',
		colSortZA: 'Z → A',
		colSortNewest: 'Mais recente',
		colSortOldest: 'Mais antigo',
		colName: 'Fonte',
		colKind: 'Tipo',
		colLane: 'Lane',
		colStatus: 'Status',
		colUpdated: 'Última atividade',
		statusActive: 'ativa',
		statusPaused: 'pausada',
		never: '—',
		count: 'fonte',
		countPlural: 'fontes',
		// actions
		newSource: 'Nova fonte',
		actionEdit: 'Editar',
		actionDelete: 'Excluir',
		actionPause: 'Pausar',
		actionResume: 'Retomar',
		// wizard
		wizardStep1Title: 'Escolha o tipo da fonte',
		wizardStep2Title: 'Configurar {kind}',
		wizardBack: '← Voltar',
		wizardCancel: 'Cancelar',
		wizardCreate: 'Criar fonte',
		wizardCreating: 'Criando…',
		wizardRequired: 'Campo obrigatório.',
		wizardCreateOk: 'Fonte criada.',
		wizardCreateError: 'Não foi possível criar a fonte.',
		// edit
		editTitle: 'Editar fonte',
		editDisplayName: 'Nome de exibição',
		editTags: 'Tags',
		editTagAdd: 'Adicionar tag…',
		editTagRemove: 'Remover tag',
		editSave: 'Salvar',
		editSaving: 'Salvando…',
		editSaveOk: 'Fonte atualizada.',
		editSaveError: 'Não foi possível salvar a fonte.',
		editLoading: 'Carregando campos…',
		// delete
		deleteTitle: 'Excluir fonte',
		deleteConfirm: 'Excluir “{name}”? O cadastro some da lista; o conteúdo já coletado é preservado.',
		deleteCancel: 'Cancelar',
		deleteConfirmBtn: 'Excluir',
		deleting: 'Excluindo…',
		deleteOk: 'Fonte excluída.',
		deleteError: 'Não foi possível excluir a fonte.',
		// pause/resume toasts
		pauseOk: 'Fonte pausada.',
		resumeOk: 'Fonte retomada.',
		pauseError: 'Não foi possível alterar o status.',
		// pagination (server-side) — every page is reachable, so there is no truncation notice
		pageRange: '{from}–{to} de {total}',
		pagePrev: 'Página anterior',
		pageNext: 'Próxima página',
		pageOf: '{page}/{pages}',
		// selection + bulk
		selectAllPage: 'Selecionar a página',
		selectRow: 'Selecionar fonte',
		selectAllPageBanner: 'As {n} fontes desta página estão selecionadas.',
		selectAllFilterBtn: 'Selecionar todas as {total}',
		selectAllCapNote: '(máx. {cap})',
		selectingAll: 'Selecionando…',
		selectedCount: '{n} fonte selecionada',
		selectedCountPlural: '{n} fontes selecionadas',
		bulkClear: 'Limpar seleção',
		bulkPause: 'Pausar',
		bulkResume: 'Retomar',
		bulkTag: 'Taguear',
		bulkUntag: 'Destaguear',
		bulkDelete: 'Excluir',
		bulkTagPlaceholder: 'tag…',
		bulkApplying: 'Aplicando…',
		bulkResultOk: '{ok} aplicada(s).',
		bulkResultPartial: '{ok} aplicada(s), {fail} falha(s).',
		bulkError: 'Não foi possível aplicar a ação em lote.',
		bulkDeleteTitle: 'Excluir fontes selecionadas',
		bulkDeleteConfirm:
			'Excluir {n} fonte(s)? O cadastro some da lista; o conteúdo já coletado é preservado.'
	},
	auditoria: {
		title: 'Auditoria',
		loading: 'Carregando decisões…',
		error: 'Não foi possível carregar o feed de decisões.',
		empty: 'Nenhuma decisão registrada ainda.',
		colID: 'ID',
		colItem: 'Item',
		colGate: 'Gate',
		colDecision: 'Decisão',
		colScore: 'Score',
		colWhen: 'Quando',
		keep: 'keep',
		drop: 'drop',
		defer: 'defer',
		limitLabel: 'Últimas',
		itemLink: '→'
	},
	cmdPalette: {
		placeholder: 'Ir para…',
		noResults: 'Nenhum resultado.'
	},
	settings: {
		title: 'Configurações',
		healthSection: 'Saúde do sistema',
		dbOk: 'Banco de dados',
		dbOkYes: 'OK',
		dbOkNo: 'Falhou',
		lastReconcile: 'Último reconcile',
		never: 'Nunca',
		providersTotal: 'Providers registrados',
		providersEnabled: 'Providers ativos',
		providersStale: 'Providers desatualizados',
		usageSection: 'Uso',
		distillationsTotal: 'Distillations',
		quarantineTotal: 'Quarentena',
		itemsSection: 'Items por lane e status',
		stepsSection: 'Etapas por capability e status',
		colLane: 'Lane',
		colCapability: 'Capability',
		colStatus: 'Status',
		colCount: 'Contagem',
		billingSection: 'Custos',
		billingNote: 'Custos exatos requerem o export do GCP Billing — não é possível calculá-los aqui.',
		billingLink: 'Abrir GCP Billing',
		// routing section (moved from workers)
		routingSection: 'Roteamento',
		metricsWorkersSection: 'Métricas Workers',
		workersLoadError: 'Não foi possível carregar os workers.',
		loading: 'Carregando configurações…',
		error: 'Não foi possível carregar as configurações.'
	},
	curadoria: {
		title: 'Curadoria',
		// ── abas ──────────────────────────────────────────────────────────────
		tabDecidir: 'Decidir',
		tabHistorico: 'Histórico',
		tabAjustes: 'Ajustes',
		// cockpit zones
		pulsoZone: 'Pulso',
		pulsoLabel: '~24h',
		pulsoEntrou: 'Entrou',
		pulsoManteve: 'Manteve',
		pulsoBarrou: 'Barrou',
		pulsoDuvida: 'Em dúvida',
		spineStep1: 'entrou',
		spineStep2: 'gate decidiu',
		spineStep3: 'você revisa a dúvida',
		spineStep4: 'molda o gosto',
		// ── zona fila (aba Decidir) ───────────────────────────────────────────
		filaZone: 'Revisar',
		filaSubtitle: 'aguardando · ←/→ p/ decidir',
		filaEmpty: 'Sem itens em dúvida.',
		filaComingSoon: 'em breve',
		filaKeep: 'Manter',
		filaDrop: 'Descartar',
		filaLoading: 'Carregando fila…',
		filaError: 'Não foi possível carregar a fila.',
		filaWhyFence: 'Por que não consegui decidir:',
		filaDecidedBy: 'Decidido por',
		filaReason: 'Motivo',
		filaScore: 'Score',
		filaReviewError: 'Erro ao registrar veredito.',
		// ── filtros (aba Decidir) ─────────────────────────────────────────────
		filterDateFrom: 'De',
		filterDateTo: 'Até',
		filterTipo: 'Tipo',
		filterCanal: 'Canal',
		filterSortBy: 'Ordenar',
		filterSortNewest: 'Mais recente',
		filterSortOldest: 'Mais antigo',
		filterClear: 'Limpar filtros',
		filterTipoTodos: 'Todos',
		filterCanalPlaceholder: 'ex: Lex Fridman',
		// ── zona gosto → ajustes ─────────────────────────────────────────────
		gostoZone: 'Ajustes',
		gostoNovaVersaoBtn: '+ Nova versão',
		gostoNovaVersaoCancelar: 'Cancelar',
		gostoNoDiff: 'Sem diferença em relação à versão ativa. Altere ao menos um campo para salvar.',
		// ── zona trilha → histórico ───────────────────────────────────────────
		trilhaZone: 'Histórico',
		trilhaLane: 'Tipo',
		trilhaSourceLink: 'Fonte',
		trilhaEmpty: 'Sem decisões registradas.',
		trilhaLoading: 'Carregando decisões…',
		trilhaError: 'Não foi possível carregar as decisões.',
		trilhaItemRef: 'item',
		trilhaDecidedByLabel: 'por',
		pulsoLoading: 'Carregando…',
		pulsoError: 'Não foi possível carregar.',
		pulsoProposedPending: 'Revisão de perfil pendente →',
		gateExpand: 'Expandir',
		gateCollapse: 'Recolher',
		profileSection: 'Interest Profile',
		profileLoading: 'Carregando interest profile…',
		profileError: 'Não foi possível carregar o interest profile.',
		profileEmpty: 'Nenhum interest profile ativo. Proponha a primeira versão abaixo.',
		profileCurrent: 'Versão ativa',
		profileNone: 'Nenhuma versão ativa.',
		profileVersions: 'Histórico de versões',
		profileVersion: 'Versão',
		profileStatus: 'Status',
		profileCreatedAt: 'Criado em',
		profileNarrative: 'Narrativa',
		profileApprove: 'Aprovar',
		profileApproving: 'Aprovando…',
		profileApproveError: 'Erro ao aprovar versão.',
		profileProposeSection: 'Propor nova versão',
		profileVersionLabel: 'Versão (inteiro positivo)',
		profileNarrativeLabel: 'Narrativa',
		profileTopicsLabel: 'Topics (JSON)',
		profileAuthorsLabel: 'Authors (JSON)',
		profileAntiTopicsLabel: 'Anti-topics (JSON)',
		profileWeightsLabel: 'Weights (JSON)',
		profileProposeBtn: 'Propor versão',
		profileProposing: 'Propondo…',
		profileProposeError: 'Erro ao propor versão.',
		profileJsonHint: 'JSON opcional — ex: ["go","observabilidade"]',
		profileStable: 'Perfil estável, sem revisão pendente.',
		profileProposedCard: 'revisão proposta',
		profileProposedNarrative: 'Narrativa do juiz',
		profileDiffAdded: 'adicionado',
		profileDiffRemoved: 'removido',
		profileDiffChanged: 'alterado',
		profileDiffNoChanges: 'Sem alterações neste campo.',
		profileDiffFallback: 'Formato inesperado — diferença não computada.',
		profileApproveBtn: (v: number) => `Aprovar v${v}`,
		profileApproveRefreshNotice: 'Aprovado! Recarregue a página para ver o histórico atualizado.',
		gateSection: 'Regras de gate',
		gateLoading: 'Carregando regras…',
		gateError: 'Não foi possível carregar as regras.',
		gateEmpty: 'Nenhuma regra configurada.',
		gateAction: 'Ação',
		gateMatchType: 'Tipo de match',
		gateValue: 'Valor',
		gateEnabled: 'Ativa',
		gateSave: 'Salvar regra',
		gateSaving: 'Salvando…',
		gateSaveError: 'Erro ao salvar regra.',
		gateEdit: 'Editar',
		gateToggle: 'Ligar/desligar',
		gateAddSection: 'Adicionar / editar regra'
	}
};
