#!/usr/bin/env bash
# install-agent-mac.sh — installs rara-runner agent as a resident launchd daemon on macOS.
# Run once to set up; re-run after `make build` to update the binary.
#
# Usage: bash install-agent-mac.sh (from the rara-runner/ directory)
set -euo pipefail

INSTALL_DIR="$HOME/.rara-runner"
PLIST_PATH="$HOME/Library/LaunchAgents/com.rara.runner-agent.plist"
LOG_DIR="$HOME/Library/Logs/rara-runner-agent"
LABEL="com.rara.runner-agent"

# ---------------------------------------------------------------------------
# 0. Directory guard — must be run from rara-runner/
# ---------------------------------------------------------------------------
if [ ! -f "go.mod" ] || [ ! -f "deploy/agent.env.example" ]; then
    echo "!! Run this script from the rara-runner/ directory:"
    echo "   cd rara-runner && bash install-agent-mac.sh"
    exit 1
fi

# ---------------------------------------------------------------------------
# 1. Prerequisites
# ---------------------------------------------------------------------------
echo "==> Checking prerequisites..."
if ! command -v go >/dev/null 2>&1; then
    echo "!! Missing: go"
    echo "   brew install go"
    exit 1
fi
if ! command -v docker >/dev/null 2>&1; then
    echo "!! Missing: docker"
    echo "   Install Docker Desktop: https://www.docker.com/products/docker-desktop/"
    echo "   Or via Homebrew: brew install --cask docker"
    exit 1
fi
echo "   go:     $(command -v go)"
echo "   docker: $(command -v docker)"

# ---------------------------------------------------------------------------
# 2. Create directories
# ---------------------------------------------------------------------------
mkdir -p "$INSTALL_DIR" "$LOG_DIR"

# ---------------------------------------------------------------------------
# 3. Create agent.env if it does not exist (exits here on first run)
# ---------------------------------------------------------------------------
if [ ! -f "$INSTALL_DIR/agent.env" ]; then
    echo ""
    echo "==> Creating $INSTALL_DIR/agent.env from template..."
    # install -m 600 creates the file with restrictive permissions atomically,
    # avoiding the brief world-readable window that cp + chmod would leave.
    install -m 600 deploy/agent.env.example "$INSTALL_DIR/agent.env"
    echo ""
    echo "!! REQUIRED STEP: edit the file before continuing:"
    echo "   \$EDITOR $INSTALL_DIR/agent.env"
    echo ""
    echo "   Fill in:"
    echo "     RUNNER_ADDR              — your Mac's Tailscale IP and port, e.g. 100.x.x.x:8473"
    echo "     RUNNER_TOKEN             — shared Bearer token (same value on dispatch side)"
    echo "     RUNNER_ALLOWED_IMAGES    — app=image@sha256:DIGEST pairs for workers to run on Mac"
    echo "     RUNNER_WORKER_ENV_FILE   — path to a KEY=VAL file with host-side secrets (DATABASE_URL, etc.)"
    echo ""
    echo "   Then run again: bash install-agent-mac.sh"
    exit 0
fi

# ---------------------------------------------------------------------------
# 4. Build the binary (native Darwin — current arch)
# ---------------------------------------------------------------------------
echo ""
echo "==> Building rara-runner..."
go build -ldflags="-w -s" -o "$INSTALL_DIR/rara-runner" .
echo "   Binary: $INSTALL_DIR/rara-runner"

# ---------------------------------------------------------------------------
# 5. Wrapper script sourced by launchd
# ---------------------------------------------------------------------------
# launchd agents have a minimal environment; the wrapper adds Homebrew to PATH
# (so `docker` is found) and sources agent.env before exec-ing the binary.
cat > "$INSTALL_DIR/run-agent.sh" << WRAPPER
#!/bin/bash
# Generated by install-agent-mac.sh — do not edit directly.
# Adds Homebrew to PATH so docker is found in launchd's minimal environment.
export PATH="/opt/homebrew/bin:/usr/local/bin:\$PATH"
set -a
source "$INSTALL_DIR/agent.env"
set +a
exec "$INSTALL_DIR/rara-runner" agent
WRAPPER
chmod 500 "$INSTALL_DIR/run-agent.sh"

# ---------------------------------------------------------------------------
# 6. Generate and install the launchd plist
# ---------------------------------------------------------------------------
mkdir -p "$(dirname "$PLIST_PATH")"
cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$INSTALL_DIR/run-agent.sh</string>
    </array>

    <!-- Resident HTTP daemon: restart on crash, start at login.
         ThrottleInterval caps restart frequency to prevent spin loops on startup crashes. -->
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>RunAtLoad</key>
    <true/>

    <key>WorkingDirectory</key>
    <string>$INSTALL_DIR</string>

    <key>StandardOutPath</key>
    <string>$LOG_DIR/output.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/error.log</string>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------------------
# 7. Load (or reload) the launchd agent
# ---------------------------------------------------------------------------
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

# ---------------------------------------------------------------------------
# 8. Final instructions
# ---------------------------------------------------------------------------
echo ""
echo "==> rara-runner agent installed and running."
echo ""
echo "   Config:  $INSTALL_DIR/agent.env"
echo "   Binary:  $INSTALL_DIR/rara-runner"
echo "   Logs:    $LOG_DIR/"
echo "   Plist:   $PLIST_PATH"
echo ""
echo "Useful commands:"
echo "  Check status:        launchctl list | grep rara.runner"
echo "  Health check:        curl -s http://\$(grep RUNNER_ADDR $INSTALL_DIR/agent.env | cut -d= -f2)/healthz"
echo "  Watch logs (live):   tail -f $LOG_DIR/error.log"
echo "  Stop agent:          launchctl unload $PLIST_PATH"
echo "  Start agent:         launchctl load $PLIST_PATH"
echo "  Update binary:       cd rara-runner && make build && bash install-agent-mac.sh"
echo ""
echo "Next steps:"
echo "  1. Confirm Tailscale is up: tailscale status"
echo "  2. Confirm Docker is running: docker info"
echo "  3. Validate the agent is reachable from dispatch:"
echo "       RUNNER_ADDR value from $INSTALL_DIR/agent.env"
echo "       curl -s http://<RUNNER_ADDR>/healthz   (from the dispatch host)"
echo "  4. Add workers to the console with runtime=local and runner_url=http://<RUNNER_ADDR>"
