#!/usr/bin/env bash
# install-local.sh — installs rara-scribe as a launchd agent on macOS.
# Run once to set up; re-run after `make build` to update the binary.
#
# Usage: bash install-local.sh (from the rara-scribe/ directory)
set -euo pipefail

INSTALL_DIR="$HOME/.rara-scribe"
PLIST_PATH="$HOME/Library/LaunchAgents/com.rara.scribe.plist"
LOG_DIR="$HOME/Library/Logs/rara-scribe"
LABEL="com.rara.scribe"

# ---------------------------------------------------------------------------
# 0. Directory guard — must be run from rara-scribe/
# ---------------------------------------------------------------------------
if [ ! -f "go.mod" ] || [ ! -f ".env.example" ]; then
    echo "!! Run this script from the rara-scribe/ directory:"
    echo "   cd rara-scribe && bash install-local.sh"
    echo "   (or: make install-local)"
    exit 1
fi

# ---------------------------------------------------------------------------
# 1. Prerequisites
# ---------------------------------------------------------------------------
echo "==> Checking prerequisites..."
missing=()
for cmd in go yt-dlp ffmpeg; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        missing+=("$cmd")
    fi
done
if [ ${#missing[@]} -gt 0 ]; then
    echo ""
    echo "!! Missing commands: ${missing[*]}"
    echo "   Install via Homebrew:"
    echo "     brew install go yt-dlp ffmpeg"
    exit 1
fi
echo "   go: $(command -v go)"
echo "   yt-dlp: $(command -v yt-dlp)"
echo "   ffmpeg: $(command -v ffmpeg)"

# ---------------------------------------------------------------------------
# 2. Create directories
# ---------------------------------------------------------------------------
mkdir -p "$INSTALL_DIR" "$LOG_DIR"

# ---------------------------------------------------------------------------
# 3. Create .env if it does not exist (exits here on first run)
# ---------------------------------------------------------------------------
if [ ! -f "$INSTALL_DIR/.env" ]; then
    echo ""
    echo "==> Creating $INSTALL_DIR/.env from template..."
    YT_DLP_REAL=$(command -v yt-dlp)
    FFMPEG_REAL=$(command -v ffmpeg)
    sed \
        -e "s|YT_DLP_BIN=.*|YT_DLP_BIN=$YT_DLP_REAL|" \
        -e "s|FFMPEG_BIN=.*|FFMPEG_BIN=$FFMPEG_REAL|" \
        .env.example > "$INSTALL_DIR/.env"
    echo ""
    echo "!! REQUIRED STEP: edit the file before continuing:"
    echo "   \$EDITOR $INSTALL_DIR/.env"
    echo ""
    echo "   Fill in DATABASE_URL and GROQ_API_KEY with real values."
    echo "   yt-dlp and ffmpeg paths have already been detected automatically."
    echo ""
    echo "   Then run again: bash install-local.sh"
    exit 0
fi

# ---------------------------------------------------------------------------
# 4. Build the binary
# ---------------------------------------------------------------------------
echo ""
echo "==> Building rara-scribe..."
go build -ldflags="-w -s" -o "$INSTALL_DIR/rara-scribe" .
echo "   Binary: $INSTALL_DIR/rara-scribe"

# ---------------------------------------------------------------------------
# 5. Wrapper script called by launchd
# ---------------------------------------------------------------------------
cat > "$INSTALL_DIR/run.sh" << WRAPPER
#!/bin/bash
# Generated by install-local.sh — do not edit directly.
# Add Homebrew to PATH so yt-dlp can find ffmpeg/ffprobe (launchd has minimal PATH).
export PATH="/opt/homebrew/bin:/usr/local/bin:\$PATH"
set -a
source "$INSTALL_DIR/.env"
set +a
exec "$INSTALL_DIR/rara-scribe"
WRAPPER
chmod +x "$INSTALL_DIR/run.sh"

# ---------------------------------------------------------------------------
# 6. Generate and install the launchd plist
# ---------------------------------------------------------------------------
mkdir -p "$(dirname "$PLIST_PATH")"
cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$INSTALL_DIR/run.sh</string>
    </array>

    <!-- Runs daily at 02:00. To change the schedule, edit this plist and
         reload: launchctl unload $PLIST_PATH && launchctl load $PLIST_PATH -->
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>2</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>

    <key>StandardOutPath</key>
    <string>$LOG_DIR/output.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/error.log</string>

    <!-- Does not run immediately on load, only at the next scheduled time -->
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------------------
# 7. Load (or reload) the launchd agent
# ---------------------------------------------------------------------------
# Unload silently if already loaded (update)
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

# ---------------------------------------------------------------------------
# 8. Final instructions
# ---------------------------------------------------------------------------
echo ""
echo "✅ rara-scribe installed and scheduled (daily at 02:00)."
echo ""
echo "   Config:  $INSTALL_DIR/.env"
echo "   Binary:  $INSTALL_DIR/rara-scribe"
echo "   Logs:    $LOG_DIR/"
echo "   Plist:   $PLIST_PATH"
echo ""
echo "Useful commands:"
echo "  Force a run now:     launchctl start $LABEL"
echo "  Watch logs (live):   tail -f $LOG_DIR/output.log"
echo "  Watch errors:        tail -f $LOG_DIR/error.log"
echo "  Stop service:        launchctl unload $PLIST_PATH"
echo "  Update binary:       cd rara-scribe && make build && bash install-local.sh"
echo ""
echo "Validate in Neon after the first run:"
echo "  SELECT status, COUNT(*) FROM transcripts GROUP BY status;"
